name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Publish script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
